DROP TABLE IF EXISTS ai_review_record;
DROP TABLE IF EXISTS daily_learning_record;
DROP TABLE IF EXISTS user_wrong_question;
DROP TABLE IF EXISTS user_favorite;
DROP TABLE IF EXISTS user_answer_record;
DROP TABLE IF EXISTS question_tag_relation;
DROP TABLE IF EXISTS question_tag;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  nickname VARCHAR(64),
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(128),
  phone VARCHAR(32),
  status TINYINT NOT NULL DEFAULT 1,
  last_login_time TIMESTAMP,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_user_username UNIQUE (username)
);

CREATE TABLE sys_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code VARCHAR(64) NOT NULL,
  role_name VARCHAR(64) NOT NULL,
  description VARCHAR(255),
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_role_code UNIQUE (role_code)
);

CREATE TABLE sys_user_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_user_role_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE question (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  answer_reference CLOB,
  correct_answer CLOB,
  analysis CLOB,
  difficulty VARCHAR(32) NOT NULL DEFAULT 'EASY',
  question_type VARCHAR(64) NOT NULL,
  creator_id BIGINT,
  source VARCHAR(128),
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_question_difficulty ON question (difficulty);
CREATE INDEX idx_question_type ON question (question_type);
CREATE INDEX idx_question_create_time ON question (create_time);
CREATE INDEX idx_sys_user_status ON sys_user (status);
CREATE INDEX idx_sys_user_create_time ON sys_user (create_time);

CREATE TABLE question_tag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_name VARCHAR(64) NOT NULL,
  description VARCHAR(255),
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_question_tag_name UNIQUE (tag_name)
);

CREATE TABLE question_tag_relation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_question_tag_relation UNIQUE (question_id, tag_id)
);

CREATE INDEX idx_question_tag_relation_question_id ON question_tag_relation (question_id);
CREATE INDEX idx_question_tag_relation_tag_id ON question_tag_relation (tag_id);

CREATE TABLE user_answer_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  question_id BIGINT NOT NULL,
  user_answer CLOB NOT NULL,
  answer_content CLOB,
  is_correct TINYINT,
  score DECIMAL(5,2),
  answer_duration INT NOT NULL DEFAULT 0,
  review_summary VARCHAR(512),
  answer_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_user_answer_record_user_time ON user_answer_record (user_id, create_time);
CREATE INDEX idx_user_answer_record_user_question ON user_answer_record (user_id, question_id);
CREATE INDEX idx_user_answer_record_question_time ON user_answer_record (question_id, create_time);
CREATE INDEX idx_user_answer_record_create_time_is_correct ON user_answer_record (create_time, is_correct);

CREATE TABLE user_favorite (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  question_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_user_favorite_user_question UNIQUE (user_id, question_id)
);

CREATE INDEX idx_user_favorite_user_time ON user_favorite (user_id, create_time);

CREATE TABLE user_wrong_question (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  question_id BIGINT NOT NULL,
  wrong_count INT NOT NULL DEFAULT 1,
  last_wrong_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_user_wrong_question_user_question UNIQUE (user_id, question_id)
);

CREATE INDEX idx_user_wrong_question_user_status ON user_wrong_question (user_id, status);
CREATE INDEX idx_user_wrong_question_user_last_wrong_time ON user_wrong_question (user_id, last_wrong_time);

CREATE TABLE daily_learning_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  record_date DATE NOT NULL,
  answer_count INT NOT NULL DEFAULT 0,
  correct_count INT NOT NULL DEFAULT 0,
  study_duration INT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_daily_learning_record_user_date UNIQUE (user_id, record_date)
);

CREATE INDEX idx_daily_learning_record_user_record_date ON daily_learning_record (user_id, record_date);
CREATE INDEX idx_daily_learning_record_record_date ON daily_learning_record (record_date);

CREATE TABLE ai_review_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  question_id BIGINT,
  answer_record_id BIGINT,
  record_type VARCHAR(64) NOT NULL DEFAULT 'ANSWER_REVIEW',
  input_content CLOB,
  result_content CLOB,
  model_name VARCHAR(128),
  interviewer_type VARCHAR(32) NOT NULL DEFAULT 'STARTUP',
  prompt CLOB,
  review_result CLOB,
  score DECIMAL(5,2),
  share_token VARCHAR(128),
  is_public BOOLEAN DEFAULT FALSE,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_ai_review_record_user_type_time ON ai_review_record (user_id, record_type, create_time);
CREATE INDEX idx_ai_review_record_question_id ON ai_review_record (question_id);
CREATE INDEX idx_ai_review_record_create_time ON ai_review_record (create_time);
CREATE INDEX idx_ai_review_record_interviewer_type ON ai_review_record (interviewer_type);
CREATE UNIQUE INDEX uk_ai_review_record_share_token ON ai_review_record (share_token);
CREATE INDEX idx_ai_review_record_is_public ON ai_review_record (is_public);

CREATE TABLE interview_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  position_model VARCHAR(128) NOT NULL,
  company_type VARCHAR(32) NOT NULL DEFAULT 'STARTUP',
  difficulty VARCHAR(32) NOT NULL,
  question_count INT NOT NULL DEFAULT 5,
  focus_areas CLOB,
  scoring_weights CLOB,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_interview_template_user_time ON interview_template (user_id, create_time);
CREATE INDEX idx_interview_template_company_difficulty ON interview_template (company_type, difficulty);

CREATE TABLE ai_interview_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  review_record_id BIGINT,
  interviewer_type VARCHAR(32) NOT NULL DEFAULT 'STARTUP',
  status VARCHAR(32) NOT NULL DEFAULT 'IN_PROGRESS',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_ai_interview_session_user_status ON ai_interview_session (user_id, status);
CREATE INDEX idx_ai_interview_session_record ON ai_interview_session (review_record_id);
CREATE INDEX idx_ai_interview_session_interviewer_type ON ai_interview_session (interviewer_type);
